[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

[project]
name = 'fine-coverage'
description = 'x'
readme = 'README.rst'
requires-python = '>=3.11'
license = 'GPL'
keywords = []
authors = [
  { name = 'Philipp A.', email = 'flying-sheep@web.de' },
]
classifiers = [
  'Development Status :: 4 - Beta',
  'Programming Language :: Python',
  'Programming Language :: Python :: 3.11',
  'Programming Language :: Python :: Implementation :: CPython',
  'Programming Language :: Python :: Implementation :: PyPy',
]
dependencies = []
dynamic = ['version']

[project.urls]
Documentation = 'https://github.com/flying-sheep/fine-coverage#readme'
Issues = 'https://github.com/flying-sheep/fine-coverage/issues'
Source = 'https://github.com/flying-sheep/fine-coverage'

[tool.hatch.version]
path = 'fine_coverage/__about__.py'

[tool.hatch.envs.default]
dependencies = [
  'pytest',
  'pytest-cov',
]
[tool.hatch.envs.default.scripts]
cov = 'pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=fine_coverage --cov=tests'
no-cov = 'cov --no-cov'

[[tool.hatch.envs.test.matrix]]
python = ['311']

[tool.coverage.run]
branch = true
parallel = true
omit = [
  'fine_coverage/__about__.py',
]

[tool.coverage.report]
exclude_lines = [
  'no cov',
  'if __name__ == .__main__.:',
  'if TYPE_CHECKING:',
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
