name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTEST_ADDOPTS: --color=yes

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: pip
        cache-dependency-path: '**/pyproject.toml'
    - run: pip install --upgrade pip wheel hatch
    - id: hatch
      run: |
        hatch env create || exit 1
        echo "venv=$(hatch env find)" >> $GITHUB_OUTPUT
    - uses: jakebailey/pyright-action@v1
      with:
        version: '2.2.1'
    - name: Tests
      if: success() || failure()
      run: hatch run test -v
