name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  PYTEST_ADDOPTS: --color=yes

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: pip
    - run: pip install --upgrade pip wheel hatch
    - id: hatch
      run: |
        hatch env create || exit 1
        echo "$(hatch env find)/bin" >> $GITHUB_PATH
    - uses: jakebailey/pyright-action@v1
      with:
        version: '1.1.356'
    - name: Tests
      if: success() || failure()
      run: hatch run test -v
